/**
 * Typography heading scale + font-token helpers (Surface/Primitive support).
 *
 * Pure constant/helper module — no React, no "use client". It formalizes a
 * single, strictly-monotonic heading type scale and exposes helpers that apply
 * the correct font-family Design_Tokens:
 *   - headings use `--font-heading` (exposed by Tailwind v4 as `font-heading`)
 *   - body uses `--font-sans` (exposed by Tailwind v4 as `font-sans`)
 *
 * The font utilities are generated by Tailwind v4 from the `--font-*` custom
 * properties declared under `@theme inline` in `src/app/globals.css`.
 *
 * The numeric size map (`HEADING_SIZES_REM`) mirrors the Tailwind text-size
 * utilities used by `HEADING_SCALE` so strict monotonicity (Property 8) can be
 * checked without parsing CSS. Keep the two maps consistent.
 *
 * Design: .kiro/specs/ui-premium-polish/design.md — "Typography scale".
 * Requirements: 1.7, 1.8, 7.2.
 */

import { type ClassValue } from "clsx";

import { cn } from "@/lib/cn";

/** Heading levels in hierarchy order, largest (h1) first. */
export const HEADING_LEVELS = ["h1", "h2", "h3", "h4"] as const;

/** A supported heading level. */
export type HeadingLevel = (typeof HEADING_LEVELS)[number];

/**
 * Maps each heading level to exactly one Tailwind type-size utility.
 *
 * Strictly DECREASING by level: h1 (largest) > h2 > h3 > h4. Mapped to
 * existing Tailwind utilities; mirrored numerically by `HEADING_SIZES_REM`.
 */
export const HEADING_SCALE = {
  h1: "text-5xl", // largest
  h2: "text-3xl",
  h3: "text-xl",
  h4: "text-base",
} as const satisfies Record<HeadingLevel, string>;

/**
 * Numeric font size (in rem) for each heading level, matching the rem value of
 * the corresponding Tailwind utility in `HEADING_SCALE`:
 *   text-5xl = 3rem, text-3xl = 1.875rem, text-xl = 1.25rem, text-base = 1rem.
 *
 * Exposed so the strict-monotonicity property (Property 8) is testable without
 * parsing CSS. MUST stay consistent with `HEADING_SCALE`.
 */
export const HEADING_SIZES_REM = {
  h1: 3,
  h2: 1.875,
  h3: 1.25,
  h4: 1,
} as const satisfies Record<HeadingLevel, number>;

/** Tailwind utility that applies the `--font-heading` Design_Token (Req 1.7). */
export const HEADING_FONT_CLASS = "font-heading";

/** Tailwind utility that applies the `--font-sans` Design_Token (Req 1.8). */
export const BODY_FONT_CLASS = "font-sans";

/**
 * Resolves a heading level to its numeric font size in rem.
 *
 * Pure and deterministic; provided so callers and the monotonicity property
 * can compare sizes numerically rather than parsing the class string.
 *
 * @param level The heading level (h1..h4).
 * @returns The font size in rem for that level.
 */
export function headingSizeRem(level: HeadingLevel): number {
  return HEADING_SIZES_REM[level];
}

/**
 * Builds the className for a heading at the given level.
 *
 * Combines the level's type-size utility (`HEADING_SCALE`) with the heading
 * font utility (`--font-heading`, Req 1.7). Any extra classes are merged via
 * `cn`, so callers can override or extend without specificity surprises.
 *
 * @param level The heading level (h1..h4).
 * @param extra Optional additional classes to merge.
 * @returns A merged className string.
 */
export function headingClass(level: HeadingLevel, ...extra: ClassValue[]): string {
  return cn(HEADING_SCALE[level], HEADING_FONT_CLASS, ...extra);
}

/**
 * Builds the className for body text.
 *
 * Applies the body font utility (`--font-sans`, Req 1.8). Any extra classes are
 * merged via `cn`.
 *
 * @param extra Optional additional classes to merge.
 * @returns A merged className string.
 */
export function bodyClass(...extra: ClassValue[]): string {
  return cn(BODY_FONT_CLASS, ...extra);
}
